name 'learn_chef_apache2'
maintainer 'Srinivasan Arumugam'
maintainer_email 'srinithin@gmail.com'
license 'all_rights'
description 'Installs/Configures learn_chef_apache2'
long_description 'Installs/Configures learn_chef_apache2'
version '0.2.0'
